const fs = require('fs'); 
const oldHome = fs.readFileSync('old_home.txt', 'utf8'); 
const currentHome = fs.readFileSync('src/pages/Home.tsx', 'utf8'); 
const topPart = currentHome.substring(0, currentHome.indexOf('  return (')); 
let newReturn = oldHome; 

newReturn = newReturn.replace(/<span className="inline-block py-1 px-3 rounded-full bg-white\/10 border border-white\/20 text-blue-200 text-sm font-medium mb-6 backdrop-blur-sm">\s*Join Our Next Gathering\s*<\/span>/, '{nextEvent ? <span className="inline-block py-1 px-3 rounded-full bg-white/10 border border-white/20 text-blue-200 text-sm font-medium mb-6 backdrop-blur-sm\">Next Upcoming Event</span> : <span className="inline-block py-1 px-3 rounded-full bg-white/10 border border-white/20 text-blue-200 text-sm font-medium mb-6 backdrop-blur-sm\">Join Our Next Gathering</span>}'); 

newReturn = newReturn.replace(/<h1 className="text-4xl md:text-6xl lg:text-7xl font-bold mb-6 tracking-tight">\s*Event Registration <span className="text-secondary italic">Platform<\/span>\s*<\/h1>/, '{nextEvent ? <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold mb-6 tracking-tight\">{nextEvent.title}</h1> : <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold mb-6 tracking-tight\">Event Registration <span className=\"text-secondary italic\">Platform</span></h1>}'); 

newReturn = newReturn.replace(/<a href="#events" className="btn btn-secondary text-primary font-bold px-8 py-4 rounded-full shadow-lg shadow-secondary\/20 hover:shadow-secondary\/40 hover:-translate-y-1 transition-all">\s*View Upcoming Events\s*<\/a>/, '{nextEvent ? (<><button onClick={() => handleRegister(nextEvent)} className="btn btn-primary text-white font-bold px-8 py-4 rounded-full shadow-lg hover:-translate-y-1 transition-all\">Register Here</button><a href="#events" className="btn btn-secondary text-primary font-bold px-8 py-4 rounded-full shadow-lg shadow-secondary/20 hover:shadow-secondary/40 hover:-translate-y-1 transition-all ml-4\">Check Incoming Events</a></>) : <a href="#events" className="btn btn-secondary text-primary font-bold px-8 py-4 rounded-full shadow-lg shadow-secondary/20 hover:shadow-secondary/40 hover:-translate-y-1 transition-all\">Check Incoming Events</a>}'); 

newReturn = newReturn.replace(/src="https:\/\/images\.unsplash\.com\/photo-1540575467063-118cb10f643c\?q=80&w=2070&auto=format&fit=crop"/, 'src={nextEvent ? `https://images.unsplash.com/photo-[RANDOM]?q=80&w=2070&auto=format&fit=crop`.replace(\'[RANDOM]\', nextEvent.id.substring(0, 8) + \'123\') : "https://images.unsplash.com/photo-1540575467063-118cb10f643c?q=80&w=2070&auto=format&fit=crop"}'); 

newReturn = newReturn.replace(/<button \s*onClick=\{\(\) => handleRegister\(event\)\}\s*className="btn btn-primary w-full mt-auto group-hover:bg-primary-light"\s*disabled=\{!event\.requires_registration\}\s*>\s*\{event\.requires_registration \? 'Register Here' : 'Walk-in Only'\}\s*<\/button>/, '<div className="flex gap-2 mt-auto"><button onClick={() => handleRegister(event)} className="btn btn-primary flex-1 group-hover:bg-primary-light">Register Here</button><button onClick={() => handleShare(event)} className="btn btn-secondary px-3" title="Share Event" style={{ padding: \'0.75rem\' }}><Share2 size={20} /></button></div>'); 

newReturn = newReturn.replace(/<button \s*onClick=\{\(\) => setSelectedEvent\(null\)\}\s*className="btn btn-primary w-full"\s*>\s*Return to Events\s*<\/button>/, '<div className="flex flex-col sm:flex-row gap-3"><a href={`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(selectedEvent.title)}&dates=${new Date(selectedEvent.starts_at).toISOString().replace(/-|:|\\.\\d\\d\\d/g, \'\')}/${new Date(selectedEvent.ends_at).toISOString().replace(/-|:|\\.\\d\\d\\d/g, \'\')}&details=${encodeURIComponent(selectedEvent.description || \'\')}&location=${encodeURIComponent(selectedEvent.venue || \'\')}`} target="_blank" rel="noopener noreferrer" className="btn btn-secondary w-full"><Calendar size={18} className="mr-2 text-secondary" /> Add to Calendar</a><button onClick={() => setSelectedEvent(null)} className="btn btn-primary w-full">Return to Events</button></div>'); 

newReturn = newReturn.replace(/<label className="label" htmlFor="birthday">Birthday \*<\/label>\s*<input \s*id="birthday"\s*type="date" \s*required\s*className="input" \s*value=\{formData\.birthday\}\s*onChange=\{\(e\) => setFormData\(\{\.\.\.formData, birthday: e\.target\.value\}\)\}\s*\/>/, '<label className="label" htmlFor="city_address">City Address *</label><input id="city_address" type="text" required className="input" placeholder="e.g. Quezon City" value={formData.city_address} onChange={(e) => setFormData({...formData, city_address: e.target.value})} />'); 

fs.writeFileSync('src/pages/Home.tsx', topPart + newReturn + '\n}\n');
