'use client';

import { useState } from 'react';
import { PageHeader, LegacyCard } from '../shared';

export default function AnnouncementsPage() {
  const [sent, setSent] = useState(false);
  return <section className="space-y-6"><PageHeader title="Announcements" subtitle="Broadcast updates to church, ministry, network, or role groups." action={<button onClick={() => setSent(true)} className="rounded-xl bg-[#299496] px-4 py-2 text-sm font-semibold text-white">＋ New Announcement</button>} />{sent ? <p className="rounded-xl border border-[#8bcfc7] bg-[#eef9f7] px-4 py-3 text-sm text-[#16858a]">Announcement draft opened below.</p> : null}<LegacyCard><h2 className="font-serif text-xl text-[#147f84]">Targeted Announcement</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Audience<select className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 font-normal"><option>Entire Church</option><option>Ministry</option><option>Network</option><option>Role</option></select></label><label className="text-sm font-semibold">Priority<select className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 font-normal"><option>Normal</option><option>Important</option><option>Urgent</option></select></label></div><label className="mt-4 block text-sm font-semibold">Title<input className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 font-normal" placeholder="Announcement title" /></label><label className="mt-4 block text-sm font-semibold">Message<textarea rows={6} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 font-normal" placeholder="Write your announcement..." /></label><div className="mt-5 flex justify-end gap-3"><button className="rounded-xl border border-[#299496] px-4 py-2 text-sm font-semibold text-[#16858a]">Save Draft</button><button className="rounded-xl bg-[#299496] px-4 py-2 text-sm font-semibold text-white">Publish Announcement</button></div></LegacyCard></section>;
}
