'use client';

import Link from 'next/link';
import { PageHeader, LegacyCard } from '../shared';

export default function MeetingPage() {
  return <section className="mx-auto max-w-4xl space-y-6"><PageHeader title="Encode Heartlink Report" subtitle="Digitize a D-Shift Heartlink Group weekly report." action={<Link href="/dashboard" className="text-sm font-semibold text-[#16858a]">← Dashboard</Link>} /><LegacyCard><h2 className="font-serif text-xl text-[#147f84]">Meeting Details</h2><div className="mt-3 border-t border-slate-200 pt-5"><div className="grid gap-4 md:grid-cols-2"><Field label="Category" placeholder="Community" /><Field label="Topic" placeholder="e.g., Red Book Chapter 1" /><Field label="Venue" placeholder="Location of the meeting" wide /><Field label="Date" placeholder="mm/dd/yyyy" /><Field label="Time Started" placeholder="--:-- --" /><Field label="Time Ended" placeholder="--:-- --" /></div><h3 className="mt-8 border-b border-slate-200 pb-3 font-serif text-xl text-[#147f84]">Leadership</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Area Pastor" placeholder="Name of Area Pastor" /><Field label="Discipler / Coordinator" placeholder="Name of Discipler" /></div><h3 className="mt-8 border-b border-slate-200 pb-3 font-serif text-xl text-[#147f84]">Testimonies & Recommendations</h3><textarea rows={5} className="mt-4 w-full rounded-xl border border-slate-200 bg-slate-50 p-4" placeholder="Write prayer requests, testimonies, or recommendations here..." /><div className="mt-6 flex justify-end gap-3"><Link href="/dashboard" className="rounded-xl border border-[#299496] px-4 py-2 text-sm font-semibold text-[#16858a]">Cancel</Link><button className="rounded-xl bg-[#299496] px-4 py-2 text-sm font-semibold text-white">Submit Report</button></div></div></LegacyCard></section>;
}

function Field({ label, placeholder, wide = false }: { label: string; placeholder: string; wide?: boolean }) { return <label className={`text-sm font-semibold ${wide ? 'md:col-span-2' : ''}`}>{label}<input className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 font-normal" placeholder={placeholder} /></label>; }
